


######################################### USERS #########################################
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "testUser1",
    "password": "password1"
}


###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "testUser2",
    "password": "password2"
}


###
DELETE http://localhost:3000/users/638b91e628043d49956faa52
// todo


###
GET http://localhost:3000/users/


###
GET http://localhost:3000/users/:id




######################################### ENGLISHWORDS #########################################
###
POST http://localhost:3000/englishwords
Content-Type: application/json

{
    "catname": "Phrases",
    "eng": "later on",
    "rus": "как-нибудь потом"
}


###
GET http://localhost:3000/englishwords/


###
GET http://localhost:3000/englishwords/:id




######################################### ENGLISHCATEGORIES #########################################
###
POST http://localhost:3000/englishcategories
Content-Type: application/json

{
    "catname": "huy"
}


###
# PUT http://localhost:3000/englishcategories/:id
PUT http://localhost:3000/englishcategories/639bdf4f685b4e601a16dbcb
Content-Type: application/json

{
    "catname": "Nouns"
}


###
# DELETE http://localhost:3000/englishcategories/:id
DELETE http://localhost:3000/englishcategories/639ac1177bfc05cc47a3883c


###
GET http://localhost:3000/englishcategories/


###
GET http://localhost:3000/englishcategories/:id
