


######################################### AUTH #########################################
DELETE http://localhost:4000/auth/logout-all


###
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email": "lil@gmail.com",
    "password": "lil9999"
}


###
POST http://localhost:4000/auth/login
Content-Type: application/json

# {
#     "email": "rodionovjr991@gmail.com",
#     "password": "password3"
# }

{
     "email": "rodionovjr91@gmail.com",
     "password": "00000pp"
}


###
POST http://localhost:4000/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2ExNWU4ZjNiMzdlN2Q3ZDdkZjU5OTEiLCJlbWFpbCI6InJvZGlvbm92anI5OTFAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkZGJSamw5OWp1VWZvS3Q1WDRvbnRkLjh3R0VQc2xXdDdpTFExN0NtNnh6TVRFNVNwQ2hBRXEiLCJjcmVhdGVkQXQiOiIyMDIyLTEyLTIwVDA3OjA0OjQ3LjM3NVoiLCJ1cGRhdGVkQXQiOiIyMDIyLTEyLTIwVDA3OjA0OjQ3LjM3NVoiLCJfX3YiOjAsImlhdCI6MTY3MTUyMjgyOX0.-Gbsb-i32OWQURjHt5q-1EtiFUDqeSN0q57uRJ-gF4E"
}


###
POST http://localhost:4000/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzllOTMwN2M2MzUxMWUwNzllNjRkNjQiLCJlbWFpbCI6InJvZGlvbm92anI5MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRiUVQ1ZEg0ZS9qS1hjWHpFTmRhaWRPdGd3TXRlR0FId1ZKYS9oNXB5ZHN5V3g4UnkyTjhueSIsImNyZWF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDEtMDJUMTM6MTU6MjEuMjg5WiIsIl9fdiI6MCwiaWF0IjoxNjcyNjcwNDM3LCJleHAiOjE2NzI2NzIyMzd9.lY4mKA1AvlTZwt0DAr3UDn8MSxyDu31Yq7w_va1xhfg


{
    "oldpassword": "00000p",
    "newpassword": "00000ppp"
}


###
POST http://localhost:4000/auth/logout
Content-Type: application/json

{
    "refreshtoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzllOTMwN2M2MzUxMWUwNzllNjRkNjQiLCJlbWFpbCI6InJvZGlvbm92anI5MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRvQjA4cGN2WDBPR29velhVdW4ybDhPSjJSeFpWTWRmSGc1QnVvSk9BRlVxNlF1Z1JTVzVKNiIsImNyZWF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDEtMDJUMTI6NTg6NDIuMjExWiIsIl9fdiI6MCwiaWF0IjoxNjcyNjY0Njg3fQ.FiGwNGah_OovgrgpnXdBGs9kh_8Ve4lyY1r_dGuPGfg"
}




######################################### NOTES #########################################
GET http://localhost:3000/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzllOTMwN2M2MzUxMWUwNzllNjRkNjQiLCJlbWFpbCI6InJvZGlvbm92anI5MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRqYXJRWG52UFkzRkcyS1RaWGpaVXBlcGhsOFkuOHVLNVJMQ3dobkhzRS9DQ2xHcC5ERlQxLiIsImNyZWF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsInVwZGF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsIl9fdiI6MCwiaWF0IjoxNjcyMzM3MjQ4LCJleHAiOjE2NzIzMzkwNDh9.NGO6C-Djg3SLntAPOgQlnfcYc0Yhs9jezlEAFuaKW_E


###
POST http://localhost:3000/notes/
Content-Type: application/json

{
    "email": "rodionovjr91@gmail.com",
    "text": "Sosu xuj" 
}


###
GET http://localhost:3000/notes/63add93a4c7bd267d56ba886
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzllOTMwN2M2MzUxMWUwNzllNjRkNjQiLCJlbWFpbCI6InJvZGlvbm92anI5MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRqYXJRWG52UFkzRkcyS1RaWGpaVXBlcGhsOFkuOHVLNVJMQ3dobkhzRS9DQ2xHcC5ERlQxLiIsImNyZWF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsInVwZGF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsIl9fdiI6MCwiaWF0IjoxNjcyMzM3MjQ4LCJleHAiOjE2NzIzMzkwNDh9.NGO6C-Djg3SLntAPOgQlnfcYc0Yhs9jezlEAFuaKW_E


###
PUT http://localhost:3000/notes/63ad89e1adf02366d8d7082d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzllOTMwN2M2MzUxMWUwNzllNjRkNjQiLCJlbWFpbCI6InJvZGlvbm92anI5MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRqYXJRWG52UFkzRkcyS1RaWGpaVXBlcGhsOFkuOHVLNVJMQ3dobkhzRS9DQ2xHcC5ERlQxLiIsImNyZWF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsInVwZGF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsIl9fdiI6MCwiaWF0IjoxNjcyMzE5ODk4LCJleHAiOjE2NzIzMjE2OTh9.pnvW_lu7BaI00GwMPtM4fOO_9RI7cLYMtVtKcr-a2Es

{
    "email": "rodionovjr91@gmail.com",
    "text": "Ja obezjana" 
}


###
DELETE http://localhost:3000/notes/63ad89b5adf02366d8d7082b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzllOTMwN2M2MzUxMWUwNzllNjRkNjQiLCJlbWFpbCI6InJvZGlvbm92anI5MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRqYXJRWG52UFkzRkcyS1RaWGpaVXBlcGhsOFkuOHVLNVJMQ3dobkhzRS9DQ2xHcC5ERlQxLiIsImNyZWF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsInVwZGF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsIl9fdiI6MCwiaWF0IjoxNjcyMzE5ODk4LCJleHAiOjE2NzIzMjE2OTh9.pnvW_lu7BaI00GwMPtM4fOO_9RI7cLYMtVtKcr-a2Es




######################################### USERS #########################################
GET http://localhost:3000/users/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzllOTMwN2M2MzUxMWUwNzllNjRkNjQiLCJlbWFpbCI6InJvZGlvbm92anI5MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRqYXJRWG52UFkzRkcyS1RaWGpaVXBlcGhsOFkuOHVLNVJMQ3dobkhzRS9DQ2xHcC5ERlQxLiIsImNyZWF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsInVwZGF0ZWRBdCI6IjIwMjItMTItMThUMDQ6MTE6NTEuMzA3WiIsIl9fdiI6MCwiaWF0IjoxNjcyMzM3MjQ4LCJleHAiOjE2NzIzMzkwNDh9.NGO6C-Djg3SLntAPOgQlnfcYc0Yhs9jezlEAFuaKW_E

###
PUT http://localhost:3000/users/:id
Content-Type: application/json

{
    "username": "testUser999",
    "password": "password999"
}


###
DELETE http://localhost:3000/users/:id


###
GET http://localhost:3000/users/


###
GET http://localhost:3000/users/:id




######################################### ENGLISHWORDS #########################################
POST http://localhost:3000/englishwords
Content-Type: application/json

{
    "catname": "Phrases",
    "eng": "later on",
    "rus": "как-нибудь потом"
}


###
PUT http://localhost:3000/englishwords/:id
Content-Type: application/json

{
    "catname": "Phrases",
    "eng": "later on",
    "rus": "как-нибудь потом"
}


###
GET http://localhost:3000/englishwords/


###
GET http://localhost:3000/englishwords/:id




######################################### ENGLISHCATEGORIES #########################################
POST http://localhost:3000/englishcategories
Content-Type: application/json

{
    "catname": "huy"
}


###
PUT http://localhost:3000/englishcategories/639abb1972ae0bb0e641171f
Content-Type: application/json

{
    "catname": "Nouns"
}


###
# DELETE http://localhost:3000/englishcategories/:id
DELETE http://localhost:3000/englishcategories/639ac1177bfc05cc47a3883c


###
GET http://localhost:3000/englishcategories/


###
GET http://localhost:3000/englishcategories/639abb1972ae0bb0e641171f
