


######################################### AUTH #########################################
POST http://localhost:4000/users/register
Content-Type: application/json

{
    "email": "rodionovjr991@gmail.com",
    "password": "password3"
}


###
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "rodionovjr91@gmail.com",
    "password": "govnojed"
}


###
POST http://localhost:3000/refresh-token
Content-Type: application/json

{
    "token": ""
}




######################################### USERS #########################################
PUT http://localhost:3000/users/:id
Content-Type: application/json

{
    "username": "testUser999",
    "password": "password999"
}


###
DELETE http://localhost:3000/users/:id


###
GET http://localhost:3000/users/


###
GET http://localhost:3000/users/:id




######################################### NOTES #########################################
# GET http://localhost:3000/notes/:email
GET http://localhost:3000/notes/rodionovjr91@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzllOGIwNjMwY2Q5NTQ0OTA2Y2ZiZjMiLCJlbWFpbCI6InJvZGlvbm92anI5OTFAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkOEh6L2hNa0IwSlNiRTJkQzZ4ZDFIT1VFZWlPencyUWJ1eGYuY2ZFSE5ZZ2IzN2xlNnN0d2EiLCJjcmVhdGVkQXQiOiIyMDIyLTEyLTE4VDAzOjM3OjQyLjMxOVoiLCJ1cGRhdGVkQXQiOiIyMDIyLTEyLTE4VDAzOjM3OjQyLjMxOVoiLCJfX3YiOjAsImlhdCI6MTY3MTM1NTYzMywiZXhwIjoxNjcxMzU1NjQ4fQ.gZ4DHY7G0asrTuYyhmTWOEqvGjDYWF37vA0aLr118gQ


###
POST http://localhost:3000/notes/
Content-Type: application/json

{
    "email": "rodionovkr91@gmail.com",
    "text": "Ty pidor" 
}




######################################### ENGLISHWORDS #########################################
POST http://localhost:3000/englishwords
Content-Type: application/json

{
    "catname": "Phrases",
    "eng": "later on",
    "rus": "как-нибудь потом"
}


###
PUT http://localhost:3000/englishwords/:id
Content-Type: application/json

{
    "catname": "Phrases",
    "eng": "later on",
    "rus": "как-нибудь потом"
}


###
GET http://localhost:3000/englishwords/


###
GET http://localhost:3000/englishwords/:id




######################################### ENGLISHCATEGORIES #########################################
POST http://localhost:3000/englishcategories
Content-Type: application/json

{
    "catname": "huy"
}


###
# PUT http://localhost:3000/englishcategories/:id
PUT http://localhost:3000/englishcategories/639abb3b72ae0bb0e6411721
Content-Type: application/json

{
    "catname": "Verbs"
}


###
# DELETE http://localhost:3000/englishcategories/:id
DELETE http://localhost:3000/englishcategories/639ac1177bfc05cc47a3883c


###
GET http://localhost:3000/englishcategories/


###
GET http://localhost:3000/englishcategories/639abb1972ae0bb0e641171f
